### PR TITLE
Further fixes for specializing enumerations with partial enum specializaiton

### PR DESCRIPTION
**Pull request by arturbac**
After this fix good news I alsmost got json schema working that way for any enumeration
still need a bit work on interleaving.
```
template<simple_enum::enum_concept enumeration_type>
struct meta<enumeration_type>
  {
  static constexpr bool custom_write = true;
  static constexpr bool custom_read = true;
  
  static constexpr auto color_values{simple_enum::enum_names_array<enumeration_type>};
  static constexpr auto color_names{simple_enum::enum_values_array<enumeration_type>};
  static constexpr auto interleaved = simple_enum::interleave(color_names, color_values);
  static constexpr std::string_view name = simple_enum::enumeration_name_v<enumeration_type>;
  static constexpr auto value = std::apply(
    [](auto &&... args) noexcept { return glz::enumerate(std::forward<decltype(args)>(args)...); }, interleaved
  );
  };

struct test_data_t
  {
  test_enum_e enum_field;
  };

enum class Color
  {
  Red,
  Green,
  Blue
  };

consteval auto adl_enum_bounds(Color)
  {
  using enum Color;
  return simple_enum::adl_info{Red, Blue};
  }
std::string schema = glz::write_json_schema<test_data_t>();
```
```
{
  "type": [
    "object"
  ],
  "properties": {
    "enum_field": {
      "$ref": "#/$defs/test_enum_e"
    }
  },
  "additionalProperties": false,
  "$defs": {
    "test_enum_e": {
      "type": [
        "string"
      ],
      "oneOf": [
        {
          "const": "foo"
        },
        {
          "const": "foo"
        },
        {
          "description": "baz",
          "const": "bar"
        }
      ]
    }
  }
}
```

### CODE REVIEW

**Comment by stephenberry** [comment]
Sweet, thanks

**Comment by arturbac** [comment]
FYI: Got it working, soon I will make documentation and release.
Now glaze json is so powerfull for enumerations without manual coding of enumeration value string pairs
just
```
enum struct test_enum_e
  {
  foo,
  bar,
  baz
  };

consteval auto adl_enum_bounds(test_enum_e)
  {
  using enum test_enum_e;
  return simple_enum::adl_info{foo, baz};
  }
struct test_data_t
  {
  test_enum_e enum_field;
  };
std::string schema = glz::write_json_schema<test_data_t>();
```

(simple_enum/glaze_json_enum_name.hpp)[https://github.com/arturbac/simple_enum/blob/master/include/simple_enum/glaze_json_enum_name.hpp]
(tests/glaze_enum_name_ut.cc)[https://github.com/arturbac/simple_enum/blob/master/tests/glaze_enum_name_ut.cc]
```
{
  "type": [
    "object"
  ],
  "properties": {
    "enum_field": {
      "$ref": "#/$defs/test_enum_e"
    }
  },
  "additionalProperties": false,
  "$defs": {
    "test_enum_e": {
      "type": [
        "string"
      ],
      "oneOf": [
        {
          "description": "foo",
          "const": "foo"
        },
        {
          "description": "bar",
          "const": "bar"
        },
        {
          "description": "baz",
          "const": "baz"
        }
      ]
    }
  }
}
```

**Comment by stephenberry** [comment]
Fantastic! This is really helpful and cool!

**Comment by arturbac** [comment]
FYI: There is still something not right in glaze with enums:
meta<T> is respected when enum_concept == is_enum_v
```
template<simple_enum::enum_concept enumeration_type>
struct from_json<enumeration_type>
  {
```

but when it is only subset my enum specializations of enums, metais still ignored and all is handled as underlying type, would be nice to have fix for that in future,

```
template<simple_enum::bounded_enum enumeration_type>
struct from_json<enumeration_type>
  {
```

 so i would be able to change simple_enum::bounded_enum and remove static_assert
 
```
template<simple_enum::enum_concept enumeration_type>
struct from_json<enumeration_type>
  {
  static_assert(simple_enum::bounded_enum<enumeration_type>);
```

**Pull request merged**
