### PR TITLE
Extra/Unknown fields handling

### PR DESCRIPTION
**Pull request by anaelorlinski**
Pull request to show in progress code

### CODE REVIEW

**Comment by jbbjarnason** [comment]
Just a question, is `any` the correct term here? I am more inclined to `extra`.

**Comment by justend29** [comment]
> Just a question, is `any` the correct term here? I am more inclined to `extra`.

I was thinking the exact same thing. I originally thought std::any, or similar, was the topic given the name until I read more into it.

**Comment by anaelorlinski** [comment]
Indeed this is not very clear, but I took this name from the Java Implementation as explained in  https://github.com/stephenberry/glaze/issues/528
I renamed it for clarity

**Comment by stephenberry** [comment]
@anaelorlinski 
Just let me know when you're ready for me to review this pull request. Thanks for putting in this work.

**Comment by anaelorlinski** [comment]
I completely rewrote the implementation, you can start review

**Comment by stephenberry** [comment]
@anaelorlinski, your implementation looks fantastic! Really nicely written and you used the Glaze internals well, which I know takes some time to get used to.

I added a unit test for when we know the type, but the keys are unknown, and it works great.

I slightly tweaked the write code, adding a std::forward to try to encourage the compiler to inline. Not sure if it's actually needed, but it doesn't hurt.

My final request is if you could add some documentation to the markdown file I just created `docs/unknown-keys.md`, just explaining why this feature exists and how it is used.

Thanks!
Stephen

**Comment by anaelorlinski** [comment]
doc updated :)

**Comment by stephenberry** [comment]
Thanks! I'll merge it in.

**Comment by justend29** [comment]
@anaelorlinski Great work!

**Pull request merged**
