### PR TITLE
Add json partial read mode

### PR DESCRIPTION
**Pull request by vlotoshko**
<details><summary>Hello spoiler</summary>
<p>
Thank you for such an amazing library! I'm learning a lot of new stuff from it, and it looks like an endless process.

After creating a custom read specialization to read only the part of the JSON, I thought it might be helpful for others. So, I decided to make a pull request, and here we are. 

Please feel free to close this pull request if you find that this feature is unnecessary or if it is implemented in an improper way.
</p>
</details> 

### Partial read
Partial read stops the JSON reading at the moment when all required data members are populated.

**Use case:** All requests include a 'header' determining whether the request should be processed or not. It is unnecessary to read a large JSON object in its entirety every time.
```json
{
  "id": "187d3cb2-942d-484c-8271-4e2141bbadb1",
  "messageType": "not supported"
            .....
  the rest of the large JSON
}
```
Using a structure like `Header` with the `.error_on_unknown_keys = false` option can be beneficial, though the JSON is still processed until the end.
```cpp
struct Header
{
    std::string id;
    std::string messageType;
};
```
**To achieve the goal** (do not read the JSON completely) the next changes were made:
- a new concept `partial_read` was added
- a new specialization of the `from_json` was added.

**The new _partial_read_ `from_json` specialization.**

The new  `from_json` is based (was copied) from the another `from_json` specialization - `requires readable_map_t<T> || glaze_object_t<T> || reflectable<T>` and it has requirements
- `requires (glaze_object_t<T> || reflectable<T>) && partial_read<T>`

All data members are considered **required for population**; empty structs without data members are not allowed as there is nothing to read.
**The reader returns** when all member fields are populated or when the end of the JSON object is reached. In the former case, the remaining portion of the JSON object is ignored, it can be even broken. Additionally, if the required field is the last in the JSON object or is missing, the reader will proceed to read the entire JSON object as usual

Enabling the `partial_read` option in the `Header` type's metadata activates the partial reading mode for the `Header` type.
```cpp
struct glz::meta<Header>
{
    static constexpr auto partial_read = true;
};
```

### Nested partial read

Including a data type with the `partial_read` option enabled into another type, such as `AnotherType`, can lead to issues when reading `AnotherType` from the JSON. This is because the partial read can stop reading 'in the middle' of the JSON object, returning an iterator that points not to the end of this JSON object.
```cpp
struct AnotherType
{
    std::string method;
    Header header; // partial read is enabled for this data member
    int number;
};
```
To resolve this issue a new option `partial_read_nested = false` has been added to the `opts` struct. This new option impacts only the new `from_json` specialization. When all required members are populated with data, this option enables rewinding the read iterator forward to the end of the JSON object. To achieve this the `opening_counter` counter is used, it increments on an opening curly bracket symbol `{`  and decrements on a closing curly bracket symbol `}`. When the counter equals zero, it indicates that the end of the JSON object has been reached and the reader returns.

This approach closely resembles the behavior when the option `.error_on_unknown_keys = false` is used. The key difference is that the reader doesn't inspect the remaining data of the JSON object; it registers only the curly bracket symbols. It looks like it can be a little bit faster compared with the `.error_on_unknown_keys = false`  approach. Or maybe not.

<details><summary>Some Catch2 unit tests</summary>
<p>

```cpp
#include <catch2/catch_test_macros.hpp>
#include <glaze/glaze.hpp>

struct Header
{
    std::string id;
    std::string type;
};

template <>
struct glz::meta<Header>
{
    static constexpr auto partial_read = true;
};

struct AnotherType
{
    std::string method;
    Header header;
    int number;
};

// NOLINTBEGIN (readability-function-cognitive-complexity)
namespace entrance::tests
{
//clazy:excludeall=non-pod-global-static

SCENARIO("Partial read", "[partial_read]")
{
    const std::string_view EXPECTED_ID = "51e2affb-0aba-4821-ba75-f2625006eb43";
    const std::string_view EXPECTED_TYPE = "message_type";

    glz::context context{};

    WHEN("The JSON object contains all required data at the beginning")
    {
        std::string json = R"({"id":"51e2affb-0aba-4821-ba75-f2625006eb43","type":"message_type","unknown key":"value"})";

        THEN("The reader processes the JSON object only until all required data is read")
        {
            Header header;
            auto pe = glz::read<glz::opts{.error_on_unknown_keys = true}>(header, json, context);

            CHECK(pe.ec == glz::error_code::none);
            CHECK(header.id == EXPECTED_ID);
            CHECK(header.type == EXPECTED_TYPE);
        }
    }

    WHEN("The JSON object contains all required data at the beginning but is broken afterward")
    {
        // closing curly bracket is missing
        std::string json = R"({"id":"51e2affb-0aba-4821-ba75-f2625006eb43","type":"message_type","unknown key":"value")";

        THEN("The reader successfully processes the JSON object until all required data is read")
        {
            Header header;
            auto pe = glz::read<glz::opts{.error_on_unknown_keys = true}>(header, json, context);

            CHECK(pe.ec == glz::error_code::none);
            CHECK(header.id == EXPECTED_ID);
            CHECK(header.type == EXPECTED_TYPE);
        }
    }

    WHEN("The JSON object has an unknown key between the known keys")
    {
        std::string json = R"({"id":"51e2affb-0aba-4821-ba75-f2625006eb43","unknown key":"value","type":"message_type"})";

        AND_WHEN("The option error_on_unknown_keys is enabled")
        {
            Header header;
            auto pe = glz::read<glz::opts{.error_on_unknown_keys = true}>(header, json, context);

            THEN("The reader fails to process the JSON object with the error: unknown key")
            {
                CHECK(pe.ec == glz::error_code::unknown_key);
                CHECK(header.id == EXPECTED_ID);
                CHECK(header.type.empty());
            }
        }

        AND_WHEN("The option error_on_unknown_keys is disabled")
        {
            Header header;
            auto pe = glz::read<glz::opts{.error_on_unknown_keys = false}>(header, json, context);

            THEN("The reader processes the JSON object without errors")
            {
                CHECK(pe.ec == glz::error_code::none);
                CHECK(header.id == EXPECTED_ID);
                CHECK(header.type == EXPECTED_TYPE);
            }
        }
    }

    WHEN("The JSON object does not contain all required data")
    {
        std::string json = R"({"id":"51e2affb-0aba-4821-ba75-f2625006eb43","unknown key":"value"})";

        AND_WHEN("The option error_on_missing_keys is enabled")
        {
            Header header;
            auto pe = glz::read<glz::opts{.error_on_unknown_keys = false, .error_on_missing_keys = true}>(header, json, context);

            THEN("The reader processes the JSON object completely and returns the error: missing key")
            {
                CHECK(pe.ec == glz::error_code::missing_key);
                CHECK(header.id == EXPECTED_ID);
                CHECK(header.type.empty());
            }
        }

        AND_WHEN("The option error_on_missing_keys is disabled")
        {
            Header header;
            auto pe = glz::read<glz::opts{.error_on_unknown_keys = false, .error_on_missing_keys = false}>(header, json, context);

            THEN("The reader processes the JSON object till the end without errors")
            {
                CHECK(pe.ec == glz::error_code::none);
                CHECK(header.id == EXPECTED_ID);
                CHECK(header.type.empty());
            }
        }
    }
}

SCENARIO("Nested partial read", "[partial_read]")
{
    const std::string_view EXPECTED_ID = "51e2affb-0aba-4821-ba75-f2625006eb43";
    const std::string_view EXPECTED_TYPE = "message_type";
    const std::string_view EXPECTED_METHOD = "m1";
    const int EXPECTED_NUMBER = 51;

    glz::context context{};

    WHEN("The JSON object contains the struct for partial reading in the middle of the object")
    {
        std::string json = R"({"method":"m1","header":{"id":"51e2affb-0aba-4821-ba75-f2625006eb43","type":"message_type","unknown key":"value"},"number":51})";

        AND_WHEN("The option partial_read_nested is disabled")
        {
            AnotherType anoterType;
            auto pe = glz::read<glz::opts{.error_on_unknown_keys = true, .partial_read_nested = false}>(anoterType, json, context);

            THEN("The reader processes the JSON object completely and returns an error: unknown key")
            {
                CHECK(pe.ec == glz::error_code::unknown_key);
                CHECK(anoterType.method == EXPECTED_METHOD);
                CHECK(anoterType.header.id == EXPECTED_ID);
                CHECK(anoterType.header.type == EXPECTED_TYPE);

                // members that are located after the partial-read struct are NOT populated
                CHECK(anoterType.number == 0);
            }
        }

        AND_WHEN("The option partial_read_nested is enabled")
        {
            AnotherType anotherType;
            auto pe = glz::read<glz::opts{.error_on_unknown_keys = true, .partial_read_nested = true}>(anotherType, json, context);

            THEN("The reader processes the JSON object until all required data is read")
            {
                CHECK(pe.ec == glz::error_code::none);
                CHECK(anotherType.method == EXPECTED_METHOD);
                CHECK(anotherType.header.id == EXPECTED_ID);
                CHECK(anotherType.header.type == EXPECTED_TYPE);

                // members located after the partial-read struct are populated
                CHECK(anotherType.number == EXPECTED_NUMBER);
            }
        }
    }
}

} // namespace entrance::tests
// NOLINTBEGIN (readability-function-cognitive-complexity)
```

</p>
</details>

### CODE REVIEW

**Comment by stephenberry** [comment]
@vlotoshko, this looks fantastic! Thanks for your work on adding partial reading. I like the approach that you took to implement it. My one request is if you could convert your catch unit tests to boost ut unit tests within Glaze and add this to your pull request. You can just add these tests to [json_test.cpp](https://github.com/stephenberry/glaze/blob/main/tests/json_test/json_test.cpp)

**Comment by vlotoshko** [comment]
@stephenberry Sure. I've converted the tests to the Boost UT tests and added them to the end of the file.

**Comment by stephenberry** [comment]
Thanks! I'm glad to merge this in.

**Comment by stephenberry** [comment]
@vlotoshko, I just released [Glaze v4.2.0](https://github.com/stephenberry/glaze/releases/tag/v4.2.0), which brings some breaking changes to partial reading. In hindsight I should have asked for your feedback first, but it wasn't till after that I thought of searching out this pull request and letting you know these updates. The biggest change is that it removes the handling of `partial_read` within the `glz::meta` and instead relies only on the option. This enables the `glz::meta` to be used in partial reading or otherwise.

**Pull request merged**
